config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root 'welcome#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :users do
    get "show", on: :collection
    get "stats", on: :collection
  end
  resources :utility_tips do 
    get "electricity", on: :collection
    get "water", on: :collection
    get "natural_gas", on: :collection
  end
  resources :stats

  match "*path" => redirect("/"), via: :get
end

app/models/utility_tip.rb
class UtilityTip < ActiveRecord::Base
end

app/controllers/utility_tips_controller.rb
class UtilityTipsController < ApplicationController
  before_action :set_utility_tip, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, only: [:edit]

  # GET /utility_tips
  # GET /utility_tips.json
  def index
    @utility_tips = UtilityTip.all
  end

  def electricity
    @utility_tips = UtilityTip.where("utility_id = ?", 0)

    respond_to do |format|
      format.json{render json: @utility_tips.to_json}
    end
  end

  def water
    @utility_tips = UtilityTip.where("utility_id = ?", 1)

    respond_to do |format|
      format.json{render json: @utility_tips.to_json}
    end
  end

  def natural_gas
    @utility_tips = UtilityTip.where("utility_id = ?", 2)

    respond_to do |format|
      format.json{render json: @utility_tips.to_json}
    end
  end

  # GET /utility_tips/1
  # GET /utility_tips/1.json
  def show
  end

  # GET /utility_tips/new
  def new
    @utility_tip = UtilityTip.new
  end

  # GET /utility_tips/1/edit
  def edit
  end

  # POST /utility_tips
  # POST /utility_tips.json
  def create
    @utility_tip = UtilityTip.new(utility_tip_params)

    respond_to do |format|
      if @utility_tip.save
        format.html { redirect_to @utility_tip, notice: 'Utility tip was successfully created.' }
        format.json { render :show, status: :created, location: @utility_tip }
      else
        format.html { render :new }
        format.json { render json: @utility_tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utility_tips/1
  # PATCH/PUT /utility_tips/1.json
  def update
    respond_to do |format|
      if @utility_tip.update(utility_tip_params)
        format.html { redirect_to @utility_tip, notice: 'Utility tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @utility_tip }
      else
        format.html { render :edit }
        format.json { render json: @utility_tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /utility_tips/1
  # DELETE /utility_tips/1.json
  def destroy
    @utility_tip.destroy
    respond_to do |format|
      format.html { redirect_to utility_tips_url, notice: 'Utility tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utility_tip
      @utility_tip = UtilityTip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def utility_tip_params
      params.require(:utility_tip).permit(:id, :order, :text, :utility_id)
    end
end

app/helpers/utility_tips_helper.rb
module UtilityTipsHelper
end

app/views/utility_tips/_form.html.erb
<%= form_for(@utility_tip) do |f| %>
  <% if @utility_tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@utility_tip.errors.count, "error") %> prohibited this utility_tip from being saved:</h2>

      <ul>
      <% @utility_tip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order %><br>
    <%= f.text_field :order %>
  </div>
  <div class="field">
    <%= f.label :utility_id %><br>
    <%= f.select :utility_id, [["Electricity",0],["Water",1],["Natural Gas",2]] %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit "Create Utility Tip", class: "button" %>
  </div>
<% end %>

app/views/utility_tips/edit.html.erb
<h1>Editing Utility Tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @utility_tip %> |
<%= link_to 'Back', utility_tips_path %>

app/views/utility_tips/index.html.erb
<h1>Listing Utility Tips</h1>
<h3>Electricity</h3>
<table width=100%>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @utility_tips.where(utility_id: 0).order(:order).each do |utility_tip| %>
      <tr>
        <td><%= utility_tip.text %></td>
        <td><%= link_to 'Edit', edit_utility_tip_path(utility_tip) %></td>
        <td><%= link_to 'Destroy', utility_tip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Water</h3>
<table width=100%>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @utility_tips.where(utility_id: 1).order(:order).each do |utility_tip| %>
      <tr>
        <td><%= utility_tip.text %></td>
        <td><%= link_to 'Edit', edit_utility_tip_path(utility_tip) %></td>
        <td><%= link_to 'Destroy', utility_tip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Natural Gas</h3>
<table width=100%>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @utility_tips.where(utility_id: 2).order(:order).each do |utility_tip| %>
      <tr>
        <td><%= utility_tip.text %></td>
        <td><%= link_to 'Edit', edit_utility_tip_path(utility_tip) %></td>
        <td><%= link_to 'Destroy', utility_tip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Utility tip', new_utility_tip_path, class: "button" %>

</center>

app/views/utility_tips/new.html.erb
<h1>New Utility Tip</h1>

<%= render 'form' %>

<%= link_to 'Back', utility_tips_path %>

app/views/utility_tips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @utility_tip.id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @utility_tip.order %>
</p>

<p>
  <strong>Text:</strong>
  <%= @utility_tip.text %>
</p>

<%= link_to 'Edit', edit_utility_tip_path(@utility_tip) %> |
<%= link_to 'Back', utility_tips_path %>