config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root 'welcome#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :users do
    get "show", on: :collection
    get "stats", on: :collection
  end
  resources :utility_tips do 
    get "electricity", on: :collection
    get "water", on: :collection
    get "natural_gas", on: :collection
  end
  resources :stats

  match "*path" => redirect("/"), via: :get
end

app/models/stat.rb
class Stat < ActiveRecord::Base
	belongs_to :user

	# Be sure to update User model too!
	def carbon_footprint
		lbs_to_kg = 0.453592
		electricity_factor = 1.46 * lbs_to_kg
		gallons_to_liters = 3.78541
		water_factor = 0.001 * gallons_to_liters
		natural_gas_factor = 5.0
		self.electricity_usage * electricity_factor + self.water_usage * water_factor + self.natural_gas_usage + natural_gas_factor
	end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_stat, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:create]
  # GET /stats/new
  def new
    @stat = Stat.new
  end

  # GET /stats/1/edit
  def edit
  end

  # POST /stats
  # POST /stats.json
  def create
    token = params[:user_token]
    email = params[:user_email]

    user = User.find_by(authentication_token: token, email: email)
    @stat = Stat.find_by(month: params[:month], year: params[:year], user: user)

    if !@stat.present?
	    @stat = user.stats.new
		end

		@stat.electricity_usage=params[:electricity_usage].to_i
		@stat.water_usage=params[:water_usage].to_i
		@stat.natural_gas_usage=params[:natural_gas_usage].to_i
		@stat.month=params[:month]
		@stat.year=params[:year]

    respond_to do |format|
      if @stat.save
        format.html { redirect_to @stat, notice: 'Stat was successfully created.' }
        format.json { render :show, status: :created, location: @stat }
      else
        format.html { render :new }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stats/1
  # PATCH/PUT /stats/1.json
  def update
    respond_to do |format|
      if @stat.update(stat_params)
        format.html { redirect_to @stat, notice: 'Stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @stat }
      else
        format.html { render :edit }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/1
  # DELETE /stats/1.json
  def destroy
    @stat.destroy
    respond_to do |format|
      format.html { redirect_to stats_url, notice: 'Stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stat
      @stat = Stat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stat_params
      params.require(:stat).permit(:id, :user_id, :electricity_usage, :water_usage, :natural_gas_usage, :month, :year)
    end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/_form.html.erb
<%= form_for(@stat) do |f| %>
  <% if @stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stat.errors.count, "error") %> prohibited this stat from being saved:</h2>

      <ul>
      <% @stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :electricity_usage %><br>
    <%= f.text_field :electricity_usage %>
  </div>
  <div class="field">
    <%= f.label :water_usage %><br>
    <%= f.text_field :water_usage %>
  </div>
  <div class="field">
    <%= f.label :natural_gas_usage %><br>
    <%= f.text_field :natural_gas_usage %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stats/edit.html.erb
<h1>Editing Stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @stat %> |
<%= link_to 'Back', stats_path %>

app/views/stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stats</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>User</th>
      <th>Electricity usage</th>
      <th>Water usage</th>
      <th>Natural gas usage</th>
      <th>Month</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stats.each do |stat| %>
      <tr>
        <td><%= stat.id %></td>
        <td><%= stat.user_id %></td>
        <td><%= stat.electricity_usage %></td>
        <td><%= stat.water_usage %></td>
        <td><%= stat.natural_gas_usage %></td>
        <td><%= stat.month %></td>
        <td><%= stat.year %></td>
        <td><%= link_to 'Show', stat %></td>
        <td><%= link_to 'Edit', edit_stat_path(stat) %></td>
        <td><%= link_to 'Destroy', stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stat', new_stat_path %>

app/views/stats/new.html.erb
<h1>New Stat</h1>

<%= render 'form' %>

<%= link_to 'Back', stats_path %>

app/views/stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @stat.id %>
</p>

<p>
  <strong>User:</strong>
  <%= @stat.user_id %>
</p>

<p>
  <strong>Electricity usage:</strong>
  <%= @stat.electricity_usage %>
</p>

<p>
  <strong>Water usage:</strong>
  <%= @stat.water_usage %>
</p>

<p>
  <strong>Natural gas usage:</strong>
  <%= @stat.natural_gas_usage %>
</p>

<p>
  <strong>Month:</strong>
  <%= @stat.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @stat.year %>
</p>

<%= link_to 'Edit', edit_stat_path(@stat) %> |
<%= link_to 'Back', stats_path %>